name: api name
description: api description
resources:
  - path: '/'
    type: restful
    description: resource documentation
    methods:
      - httpVerb: GET
        filters:
          - filterA
          - filterB
        onAir: true
        inboundRequest:
          requestType: http
          headers: 
            - name: auth
              required: true 
          queryStrings:
            - name: id
              required: false
            - name: type
              required: false
          requestBody:
            - definitionName: modelDefinition
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: queryStrings.id
              mapTo: 1
          applicationName: BDTService
          group: test
          version: 1.0.0
          interface: com.ikurento.user.UserProvider
          Method: GetUser
          paramTypes:
            - java.lang.String
          ClusterName: test_dubbo
definitions:
  - name: modelDefinition
    schema: >-
      {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "type" : {
            "type" : "string"
          },
          "price" : {
            "type" : "number"
          }
        }
      }
