# dubbo server yaml configure file


# application config
application:
  organization: "dubbogoproxy.com"
  name: "User Micro Service"
  module: "dubbogoproxy user-info server"
  version: "0.0.1"
  owner: "ZX"
  environment: "dev"

registries:
  "zk1":
    protocol: "zookeeper"
    timeout: "3s"
    address: "127.0.0.1:2181"

services:
  "UserProvider":
    # 可以指定多个registry，使用逗号隔开;不指定默认向所有注册中心注册
    registry: "zk1"
    protocol: "dubbo"
    # 相当于dubbo.xml中的interface
    interface: "com.ic.user.UserProvider"
    loadbalance: "random"
    warmup: "100"
    cluster: "failover"
    version: 1.0.0
    group: test
    methods:
      - name: "CreateUser"
        retries: 1
      - name: "GetUser"
        retries: 1
        loadbalance: "random"
      - name: "QueryUser"
        retries: 1
        loadbalance: "random"
      - name: "TwoSimpleParams"
        retries: 1
        loadbalance: "random"

protocols:
  "dubbo":
    name: "dubbo"
    port: 20000

protocol_conf:
  dubbo:
    session_number: 700
    session_timeout: "20s"
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"
      tcp_write_timeout: "5s"
      wait_timeout: "1s"
      max_msg_len: 1024
      session_name: "server"
