name: getUserByName
description: get user by name
resources:
  - path: '/api/v1/test-dubbo/user'
    type: restful
    description: resource documentation
    filters:
      - filter0
    methods:
      - httpVerb: GET
        onAir: true
        inboundRequest:
          requestType: http
          queryStrings:
            - name: name
              required: true
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: queryStrings.name
              mapTo: 1
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "GetUserByName"
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
  - path: '/api/v1/test-dubbo/user'
    type: restful
    description: resource documentation
    filters:
      - filter0
    methods:
      - httpVerb: POST
        onAir: true
        inboundRequest:
          requestType: http
          requestBody:
            - definitionName: userCreate
        integrationRequest:
          requestType: dubbo
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "CreateUser"
          clusterName: "test_dubbo"
          group: "test"
          version: 1.0.0
definitions:
  - name: userCreate
    schema: >-
      {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "age" : {
            "type" : "integer"
          }
        }
      }
